// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqbJHf7QEgQCsG_rO4fWtdQLd_KSRD5BQ',
    appId: '1:90854589504:web:75cf36d98e1ff883028ba5',
    messagingSenderId: '90854589504',
    projectId: 'habitduel-28b8f',
    authDomain: 'habitduel-28b8f.firebaseapp.com',
    storageBucket: 'habitduel-28b8f.firebasestorage.app',
    measurementId: 'G-VM48F67TEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_qwzf1jw3OUfDZ4MWQHCe35o1FNAyS8A',
    appId: '1:90854589504:android:48df183dde8215bb028ba5',
    messagingSenderId: '90854589504',
    projectId: 'habitduel-28b8f',
    storageBucket: 'habitduel-28b8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVnPD_ebCiXw_OEOU8VriTIFm-iZ06qvA',
    appId: '1:90854589504:ios:c1cc58f43d75d506028ba5',
    messagingSenderId: '90854589504',
    projectId: 'habitduel-28b8f',
    storageBucket: 'habitduel-28b8f.firebasestorage.app',
    iosBundleId: 'com.rxritet.habitduel',
  );

}